GET https://world.openfoodfacts.org/api/v2/product/3502110009357.json HTTP/1.1
####
Post http://localhost/apiv2.1.3.7/inserter.php
Content-Type: application/json

{
  "code": "3502110009357",
  "product": {
    "abbreviated_product_name": "Pepsi max pet 1.5l",
    "brands": "Pepsi,Diet pepsi,بيبسي ماكس",
    "brands_imported": "Diet pepsi",
    "category_properties": {
      "ciqual_food_name:en": "Cola, without sugar and with artificial sweetener-s-"
    },
    "image_url": "https://images.openfoodfacts.org/images/products/350/211/000/9357/front_en.80.400.jpg",
    "ingredients_text": "carbonated water, colour (caramel e150d), sweeteners (aspartame (contains a phenylalanine source), acesulfame k), acidity regulators (phosphoric acid, citric acid, sodium citrate), flavourings (including natural extracts of plants and caffeine)",
    "labels": "Low or no sugar,Contains a source of phenylalanine,Green Dot,No sugar",
    "packagings": [
      {
        "material": "en:pet-polyethylene-terephthalate"
      }
    ]
    }
}
###
Post http://localhost/apiv2.1.3.7/getter.php
Content-Type: application/json

{"productCode":"3502110009357"}
###
Post http://localhost/api/getProduct.json
Content-Type: application/json

{"productCode":"3502110009357"}
###
GET http://localhost/api/MapScript
###
GET http://localhost/apiv2.1.3.7/Koszee.php